# Generated by Django 3.1.3 on 2021-04-17 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_works_blog', '0002_auto_20210417_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(default='A short description', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(default='Python', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='Project Title', max_length=100),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(default='Post Title', max_length=255)),
                ('body', models.TextField(default='Body of the post, add image using <img> tag')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('related_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_works_blog.project')),
            ],
            options={
                'ordering': ['post_title'],
            },
        ),
    ]
