# Generated by Django 3.1.3 on 2021-04-18 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_works_blog', '0003_auto_20210417_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='related_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_works_blog.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.TextField(default='\\images\\coding_screen_banner.jpg'),
        ),
    ]
